services:
  tasks.md:
    build: .
    container_name: tasks.md
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/Documents/local-services/tasks.md/tasks:/tasks
      - ~/Documents/local-services/tasks.md/config:/config
      - ~/Documents/local-services/tasks.md/archive:/archive
    restart: unless-stopped
    ports:
      - 9000:8080
